name: effect_core
description: Lazy typed Dart effects with structured concurrency, scoped resources and dependency provision.
version: 0.0.1
environment:
  sdk: '>=3.13.0 <4.0.0'
dev_dependencies:
  test: ^1.26.0
  lints: ^6.0.0

homepage: https://effect-dart.ginjustice4.chatgpt.site
repository: https://github.com/iamudesharma/dart-effect
issue_tracker: https://github.com/iamudesharma/dart-effect/issues
